-- ReCreatio full database wipe (SQL Server)
-- Run in the target database (e.g. USE [minmer_zap_25];)

SET NOCOUNT ON;

-- Disable constraints to allow deletes in any order
ALTER TABLE dbo.Memberships NOCHECK CONSTRAINT ALL;
ALTER TABLE dbo.RoleEdges NOCHECK CONSTRAINT ALL;
ALTER TABLE dbo.Keys NOCHECK CONSTRAINT ALL;
ALTER TABLE dbo.SharedViews NOCHECK CONSTRAINT ALL;
ALTER TABLE dbo.Sessions NOCHECK CONSTRAINT ALL;
ALTER TABLE dbo.UserAccounts NOCHECK CONSTRAINT ALL;
ALTER TABLE dbo.Roles NOCHECK CONSTRAINT ALL;
ALTER TABLE dbo.AuthLedger NOCHECK CONSTRAINT ALL;
ALTER TABLE dbo.KeyLedger NOCHECK CONSTRAINT ALL;
ALTER TABLE dbo.BusinessLedger NOCHECK CONSTRAINT ALL;

-- Delete data
DELETE FROM dbo.Memberships;
DELETE FROM dbo.RoleEdges;
DELETE FROM dbo.Keys;
DELETE FROM dbo.SharedViews;
DELETE FROM dbo.Sessions;
DELETE FROM dbo.UserAccounts;
DELETE FROM dbo.Roles;
DELETE FROM dbo.AuthLedger;
DELETE FROM dbo.KeyLedger;
DELETE FROM dbo.BusinessLedger;

-- Re-enable constraints
ALTER TABLE dbo.Memberships WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE dbo.RoleEdges WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE dbo.Keys WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE dbo.SharedViews WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE dbo.Sessions WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE dbo.UserAccounts WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE dbo.Roles WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE dbo.AuthLedger WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE dbo.KeyLedger WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE dbo.BusinessLedger WITH CHECK CHECK CONSTRAINT ALL;
