import { useCallback, useEffect, useLayoutEffect, useMemo, useRef, useState } from 'react';

/**
 * The scroll engine. Not native scrolling — the track is translated with
 * transform, which is what lets background layers move at their own rate.
 *
 * Geometry, and the reason for it:
 *   slideHeight = max(measured content height, viewport × MIN_VIEWPORT_FACTOR)
 *   travel      = slideHeight − viewport
 * The floor guarantees travel > 0 even on a slide whose content fits one
 * screen, so a tall background always has room to slide.
 *
 * ── How a slide is left ──────────────────────────────────────────────────────
 * A slide's inner range, start → innerEnd, scrolls freely: that is reading, and
 * a throw coasts through it with friction like any other scroller.
 *
 * What happens at the boundary is the whole feel of the page, and there are
 * exactly two answers:
 *
 *   **Not enough to leave.** The movement slows to a stop at the end of the
 *   slide and is spent there. A coast never stretches past an edge and never
 *   counts towards leaving: momentum is not an intention. Only a further,
 *   deliberate scroll — a finger dragging, wheel notches adding up over
 *   PULL_MEMORY_MS — pushes past it, stretching with rising resistance up to
 *   PEEK_MAX_FACTOR of a viewport so the next slide can be looked at before
 *   committing, and springing back if it is not.
 *
 *   **Enough to leave.** The reader's own scrolling reached the end of the
 *   slide and there was still a throw behind it: that remaining speed is handed
 *   straight to the transition, which picks the movement up where the throw
 *   left it and decelerates to a stop at the top of the next slide.
 *   One movement from the finger to the far side — and it ENDS
 *   there: the leftover speed is spent on the transition, the coast is stopped,
 *   and the pull is cleared, so nothing carries on into the slide just reached.
 *
 * Inertia by itself is never enough. A throw let go in the middle of a slide
 * drifts to the bottom and stops there; the next scroll is what leaves. And a
 * slide with no reading range worth the name is excluded from carrying through
 * at all — it is at its own end from the first pixel, so every twitch on it
 * would qualify, and such a page flipped between two slides.
 *
 * After any departure the input is gated. A trackpad sends deltas for up to a
 * second after the fingers leave, and a gate that merely expired let that tail
 * land in the newly arrived slide and scroll it on its own — so the gate is held
 * open by the tail itself (GATE_QUIET_MS). But only while it behaves like one:
 * momentum decays, so an event bigger than the last is a person pushing again
 * and goes straight through, and GATE_MAX_MS ends the matter regardless.
 * Without both of those the gate wedged shut against steady scrolling on a
 * wheel, and the page stopped answering until the hand came off.
 */

/** A slide is never shorter than the screen; content decides anything more. */
const MIN_VIEWPORT_FACTOR = 1;
const TRACK_INTERPOLATION = 0.24;
const WHEEL_CLAMP = 180;
/** Reading inside a slide covers ground faster than one notch of the wheel. */
const WHEEL_GAIN = 1.6;

/** How far past a slide's edge the track may be pulled, as a share of viewport. */
const PEEK_MAX_FACTOR = 0.3;
/** Share of that maximum which, once reached, commits instead of springing back. */
const PEEK_COMMIT_RATIO = 0.42;
/** A throw at least this fast (px/ms) commits regardless of how far it pulled. */
const FLICK_COMMIT_VELOCITY = 0.5;

/** Spring back to the slide you were on. */
const BOUNCE_MS = 300;
/** Carry through to the next slide. */
const SLIDE_TRANSITION_MS = 520;
/**
 * Wheel and keys have no release event. A pull that has already passed the
 * commit threshold goes at once; this is only the fallback for one that stopped
 * short and has to be sprung back.
 */
const RESOLVE_IDLE_MS = 120;
/** Breathing room after a committed move, so one burst cannot chain. */
const BOUNDARY_HOLD_MS = 90;

/**
 * How quiet the input has to go before a gate lifts.
 *
 * A trackpad keeps sending deltas for up to a second after the fingers have
 * left, and a departure takes about half of that. The tail therefore used to
 * arrive AFTER the transition had finished and scrolled the slide that had just
 * been arrived at — the "further movement" at the end of every flick. A gate
 * that merely expires cannot help; this one is pushed forward by every event it
 * swallows, so it lifts only once the stream has actually stopped.
 */
const GATE_QUIET_MS = 140;

/**
 * The longest gap that still counts as the same, continuous stream of input.
 *
 * This is what tells a trackpad's momentum from a person scrolling, and the
 * distinction is one of RATE, not of size. Momentum is generated by the browser
 * at frame rate: a delta every 16 ms or so, without a break, for up to a second
 * after the fingers have left. A hand on a wheel is nothing like that — notches
 * arrive tens or hundreds of milliseconds apart, and each is about as big as the
 * last.
 *
 * Judging by size instead, as this did at first, mistook every wheel notch for
 * more momentum: they were swallowed one after another, the gate never lifted,
 * and the page ignored somebody scrolling steadily until they stopped.
 */
const TAIL_GAP_MS = 34;

/** However quiet it never gets, a gate lets go this long after the departure. */
const GATE_MAX_MS = 1100;

/** Silence this long ends a wheel gesture; the next delta begins a new one. */
const GESTURE_GAP_MS = 180;
/**
 * How long a pull against an edge is remembered after it springs back. A mouse
 * wheel arrives as separate notches, so without this each one would peek, bounce
 * and throw its pull away, and no amount of scrolling would ever leave the
 * slide. Within this window successive scrolls the same way keep adding up.
 */
const PULL_MEMORY_MS = 1200;

/**
 * How far a finger travels before its direction counts.
 *
 * Only applied where a gesture could mean two things — inside something that
 * scrolls sideways, a wide table above all. Everywhere else the slide answers
 * from the first pixel, as it always did.
 */
const AXIS_THRESHOLD_PX = 8;

type TouchAxis = 'undecided' | 'vertical' | 'horizontal';

/**
 * The nearest ancestor that can still be panned sideways, or null.
 *
 * A table wider than the phone lives in such a box. Without this, the shell
 * swallowed every touchmove for its own vertical scroll, and the columns to the
 * right of the screen edge could not be reached by finger at all — the wheel
 * path had yielded to horizontal gestures since the beginning, the touch path
 * never did.
 */
function horizontallyScrollable(node: EventTarget | null): Element | null {
  let element = node instanceof Element ? node : null;

  while (element !== null) {
    if (element.scrollWidth > element.clientWidth + 1) {
      const overflowX = window.getComputedStyle(element).overflowX;
      if (overflowX === 'auto' || overflowX === 'scroll') return element;
    }
    element = element.parentElement;
  }

  return null;
}

/**
 * Inner travel below this is not worth scrolling through — a slide whose
 * content fits the screen has nothing to read on the way past, so its inner
 * range is treated as a single point.
 */
const SHALLOW_TRAVEL_FACTOR = 0.15;

const FLING_FRICTION = 0.94;
const FLING_MIN_VELOCITY = 0.04;
const FLING_MAX_VELOCITY = 3.2;
const VELOCITY_SMOOTHING = 0.72;

const KEY_CONSUMING_TAGS = new Set(['INPUT', 'TEXTAREA', 'SELECT', 'OPTION', 'BUTTON', 'A', 'SUMMARY']);

/** True when the focused element needs the key more than the page does. */
function ownsKeyboardInput(target: EventTarget | null): boolean {
  if (!(target instanceof HTMLElement)) return false;
  if (target.isContentEditable) return true;
  return KEY_CONSUMING_TAGS.has(target.tagName);
}

function clamp(value: number, min: number, max: number): number {
  return value < min ? min : value > max ? max : value;
}

function easeInOut(t: number): number {
  return t < 0.5 ? 4 * t * t * t : 1 - Math.pow(-2 * t + 2, 3) / 2;
}

/**
 * Starts at speed and slows to a stop — the shape a throw already has.
 *
 * Used for a departure that a fling carried into: an ease-in-out would begin
 * from a standstill, and a movement that stops and then starts again is read as
 * two movements, however short the pause.
 *
 * Its initial speed is 3 × distance ÷ duration, which is what lets the duration
 * below be chosen to match the speed the finger actually left behind.
 */
function easeOut(t: number): number {
  return 1 - Math.pow(1 - t, 3);
}

/** The ease-out's speed at t=0, as a multiple of the average. */
const EASE_OUT_KICK = 3;

/**
 * Rubber band: the first pixels of pull come through nearly whole, later ones
 * barely at all, approaching `max` without ever quite reaching it. That rising
 * resistance is what makes the edge feel like a physical stop you are stretching.
 */
function damp(raw: number, max: number): number {
  if (raw <= 0 || max <= 0) return 0;
  return (max * raw) / (raw + max);
}

function normalizeWheelDelta(event: WheelEvent): number {
  let delta = event.deltaY;
  if (event.deltaMode === 1) delta *= 16;
  else if (event.deltaMode === 2) delta *= Math.max(480, window.innerHeight * 0.85);
  return clamp(delta, -WHEEL_CLAMP, WHEEL_CLAMP) * WHEEL_GAIN;
}

export type SlideGeometry = {
  height: number;
  start: number;
  travel: number;
  /** 0 → 1 across the slide's own inner scroll. */
  progress: number;
  /**
   * 0 → 1 across the whole time the slide is on screen: from its top entering
   * at the bottom of the viewport, to its bottom leaving at the top.
   */
  visibleProgress: number;
};

type Slide = { start: number; innerEnd: number; shallow: boolean };
/** A pull past a slide edge that has not yet been resolved. */
type Peek = { index: number; direction: 1 | -1; raw: number };

export function useSlideScroll(slideCount: number) {
  const viewportRef = useRef<HTMLDivElement | null>(null);
  const contentRefs = useRef<Array<HTMLDivElement | null>>([]);
  const rafRef = useRef<number | null>(null);
  const settleRafRef = useRef<number | null>(null);
  const resolveTimerRef = useRef<number | null>(null);
  const tweenRef = useRef<{
    from: number;
    to: number;
    start: number;
    duration: number;
    ease: (t: number) => number;
  } | null>(null);
  const slidesRef = useRef<Slide[]>([]);
  const peekRef = useRef<Peek | null>(null);
  /** Pull accumulated against one edge, surviving the springs back between scrolls. */
  const pullRef = useRef<{ index: number; direction: 1 | -1; raw: number; at: number } | null>(null);
  const gateUntilRef = useRef(0);
  /** The tail of the gesture that caused a departure: size, deadline, and a cap. */
  const tailRef = useRef({ until: 0, size: 0, cap: 0 });
  const lastWheelAtRef = useRef(0);
  /** When the last delta of any kind arrived, for telling a stream from a push. */
  const lastDeltaAtRef = useRef(0);
  /**
   * Whether the reader's own scrolling — not its momentum — has reached the end
   * of the slide during this gesture.
   *
   * This is the difference between "I threw the page and it drifted to the
   * bottom" and "I scrolled to the bottom and I am still going". Only the second
   * may leave on inertia.
   */
  const reachedEdgeRef = useRef(false);
  const positionRef = useRef(0);
  const targetRef = useRef(0);
  const interpolationRef = useRef(TRACK_INTERPOLATION);
  const touchYRef = useRef<number | null>(null);
  /** Where the finger went down, so a gesture's direction can be judged. */
  const touchStartRef = useRef<{ x: number; y: number } | null>(null);
  const touchAxisRef = useRef<TouchAxis>('vertical');
  const velocityRef = useRef(0);
  const lastTouchAtRef = useRef(0);
  const maxScrollRef = useRef(0);
  const viewportRefValue = useRef(1);

  /**
   * Whether the reader has taken hold of the page yet.
   *
   * Only real input counts — a wheel, a finger, a key. Anything the shell does
   * to the track itself, above all the jump to the slide an address named, is
   * not the reader moving, and must not be mistaken for it: while this is still
   * false the shell is free to keep the track on that slide as pictures load
   * and everything below them shifts.
   */
  const [interacted, setInteracted] = useState(false);

  const [viewportHeight, setViewportHeight] = useState(1);
  const [position, setPosition] = useState(0);
  const [contentHeights, setContentHeights] = useState<number[]>(() => new Array(slideCount).fill(0));

  viewportRefValue.current = viewportHeight;

  useEffect(() => {
    setContentHeights((previous) => Array.from({ length: slideCount }, (_, index) => previous[index] ?? 0));
    contentRefs.current = contentRefs.current.slice(0, slideCount);
  }, [slideCount]);

  // ── Geometry ──────────────────────────────────────────────────────────────

  const minSlideHeight = Math.max(1, viewportHeight * MIN_VIEWPORT_FACTOR);

  const geometry = useMemo<SlideGeometry[]>(() => {
    const result: SlideGeometry[] = [];
    let start = 0;
    for (let index = 0; index < slideCount; index += 1) {
      const height = Math.max(contentHeights[index] ?? 0, minSlideHeight);
      const travel = Math.max(0, height - viewportHeight);
      result.push({
        height,
        start,
        travel,
        progress: travel > 0 ? clamp((position - start) / travel, 0, 1) : 0,
        visibleProgress: clamp((position - start + viewportHeight) / (height + viewportHeight), 0, 1)
      });
      start += height;
    }
    return result;
  }, [contentHeights, minSlideHeight, position, slideCount, viewportHeight]);

  /**
   * Whether every slide has said how tall it is.
   *
   * Not "the geometry looks plausible": until a slide has been measured it is
   * assumed to be exactly one screen tall, and a page whose slides are two or
   * three screens each is then wrong about where every one of them starts.
   * Anything that jumps to a particular slide has to wait for this, or it lands
   * in the middle of an earlier one — and the address, which follows whatever
   * slide the reader appears to be on, then reports that wrong place.
   */
  const measured = contentHeights.length === slideCount && contentHeights.every((height) => height > 0);

  const totalHeight = geometry.reduce((sum, slide) => sum + slide.height, 0);
  const maxScroll = Math.max(0, totalHeight - viewportHeight);
  maxScrollRef.current = maxScroll;

  const activeIndex = useMemo(() => {
    const probe = position + viewportHeight * 0.4;
    for (let index = geometry.length - 1; index >= 0; index -= 1) {
      if (probe >= geometry[index].start) return index;
    }
    return 0;
  }, [geometry, position, viewportHeight]);

  useEffect(() => {
    const shallowBelow = viewportHeight * SHALLOW_TRAVEL_FACTOR;
    slidesRef.current = geometry.map((slide) => ({
      start: slide.start,
      innerEnd: slide.start + slide.travel,
      shallow: slide.travel < shallowBelow
    }));
  }, [geometry, viewportHeight]);

  // ── Measurement ───────────────────────────────────────────────────────────

  useLayoutEffect(() => {
    const update = () => setViewportHeight(viewportRef.current?.clientHeight ?? window.innerHeight);
    update();
    window.addEventListener('resize', update);
    window.addEventListener('orientationchange', update);
    return () => {
      window.removeEventListener('resize', update);
      window.removeEventListener('orientationchange', update);
    };
  }, []);

  useLayoutEffect(() => {
    const measure = () => {
      setContentHeights((previous) => {
        let changed = false;
        const next = Array.from({ length: slideCount }, (_, index) => {
          const height = contentRefs.current[index]?.scrollHeight ?? 0;
          if (Math.abs((previous[index] ?? 0) - height) > 0.5) changed = true;
          return height;
        });
        return changed ? next : previous;
      });
    };

    measure();
    if (typeof ResizeObserver === 'undefined') return;

    const observer = new ResizeObserver(measure);
    for (const element of contentRefs.current) {
      if (element) observer.observe(element);
    }
    return () => observer.disconnect();
  }, [slideCount, viewportHeight]);

  // ── Animation ─────────────────────────────────────────────────────────────

  const animate = useCallback(() => {
    if (rafRef.current !== null) return;

    const tick = () => {
      const tween = tweenRef.current;

      if (tween) {
        const progress = clamp((performance.now() - tween.start) / tween.duration, 0, 1);
        const next = tween.from + (tween.to - tween.from) * tween.ease(progress);

        /**
         * Arrive, rather than approach for ever.
         *
         * An ease-out spends its last third of time covering the last few
         * percent of the distance, so the end of a transition is a sub-pixel
         * crawl: the slide has visibly arrived and something is still moving.
         * Within half a pixel of the destination there is nothing left worth
         * animating, so it stops there, exactly on it.
         */
        if (progress >= 1 || Math.abs(tween.to - next) < 0.5) {
          positionRef.current = tween.to;
          setPosition(tween.to);
          tweenRef.current = null;
          rafRef.current = null;
          return;
        }

        positionRef.current = next;
        setPosition(next);
        rafRef.current = requestAnimationFrame(tick);
        return;
      }

      const current = positionRef.current;
      const delta = targetRef.current - current;

      if (Math.abs(delta) < 0.25) {
        positionRef.current = targetRef.current;
        setPosition(targetRef.current);
        rafRef.current = null;
        return;
      }

      const next = current + delta * interpolationRef.current;
      positionRef.current = next;
      setPosition(next);
      rafRef.current = requestAnimationFrame(tick);
    };

    rafRef.current = requestAnimationFrame(tick);
  }, []);

  /** Exponential chase — responsive, used while a finger or wheel is driving. */
  const setTarget = useCallback(
    (value: number, interpolation: number = TRACK_INTERPOLATION) => {
      tweenRef.current = null;
      interpolationRef.current = interpolation;
      targetRef.current = clamp(value, 0, maxScrollRef.current);
      animate();
    },
    [animate]
  );

  /** Timed ease — the spring back, and the move between slides. */
  const tweenTo = useCallback(
    (value: number, duration: number, ease: (t: number) => number = easeInOut) => {
      const to = clamp(value, 0, maxScrollRef.current);
      targetRef.current = to;
      tweenRef.current = { from: positionRef.current, to, start: performance.now(), duration, ease };
      animate();
    },
    [animate]
  );

  const stopSettle = useCallback(() => {
    if (settleRafRef.current !== null) {
      cancelAnimationFrame(settleRafRef.current);
      settleRafRef.current = null;
    }
  }, []);

  const cancelResolveTimer = useCallback(() => {
    if (resolveTimerRef.current !== null) {
      window.clearTimeout(resolveTimerRef.current);
      resolveTimerRef.current = null;
    }
  }, []);

  // ── Peek and commit ───────────────────────────────────────────────────────

  /**
   * Applies `delta`, following past a slide edge with resistance rather than
   * stopping there. Only ever moves within the current slide plus its peek, so
   * one gesture cannot reach the slide after next.
   */
  /** Adds to the pull held against one edge, starting over if it went stale. */
  const rememberPull = useCallback((index: number, direction: 1 | -1, added: number): number => {
    const now = performance.now();
    const held = pullRef.current;
    const continues =
      held !== null && held.index === index && held.direction === direction && now - held.at <= PULL_MEMORY_MS;

    const raw = Math.max(0, (continues ? held.raw : 0) + added);
    pullRef.current = { index, direction, raw, at: now };
    return raw;
  }, []);

  const advance = useCallback(
    /**
     * `coasting` marks the call as a touch throw carrying on after release
     * rather than a hand actually driving. Momentum built up while reading is
     * not an intention to leave, so a coast never contributes to the pull.
     */
    (delta: number, coasting = false): 'moved' | 'edge' | 'peek' => {
      const slides = slidesRef.current;
      if (slides.length === 0) {
        setTarget(targetRef.current + delta);
        return 'moved';
      }

      const maxPeek = viewportRefValue.current * PEEK_MAX_FACTOR;
      const active = peekRef.current;

      // Already stretched: feed the pull, and let it be wound back to zero.
      if (active) {
        const slide = slides[active.index];
        if (!slide) {
          peekRef.current = null;
          return 'moved';
        }
        const edge = active.direction > 0 ? slide.innerEnd : slide.start;
        const raw = rememberPull(active.index, active.direction, delta * active.direction);
        active.raw = raw;

        if (raw <= 0) {
          // Wound all the way back — the reader changed their mind, so the
          // accumulation starts again from nothing.
          peekRef.current = null;
          pullRef.current = null;
          setTarget(edge);
          return 'moved';
        }
        setTarget(edge + active.direction * damp(raw, maxPeek));
        return 'peek';
      }

      const from = targetRef.current;
      let index = slides.findIndex((slide) => from <= slide.innerEnd + 0.5);
      if (index === -1) index = slides.length - 1;
      const slide = slides[index];

      /**
       * The real inner range, whatever its size.
       *
       * These used to collapse to a single point on a "shallow" slide — one
       * whose content overruns the screen by less than SHALLOW_TRAVEL_FACTOR —
       * which made that last strip of content unreachable: the page simply
       * refused to scroll the few dozen pixels needed to read it. Shallowness
       * still decides whether such a slide may be LEFT on inertia, which is what
       * it was always really about.
       */
      const lowerBound = Math.min(slide.start, slide.innerEnd);
      const upperBound = Math.max(slide.start, slide.innerEnd);
      const to = from + delta;

      /**
       * A coast that reaches a boundary stops there, full stop: it neither
       * stretches past it nor counts towards the pull that would leave.
       *
       * Momentum is not an intention. The caller decides separately whether the
       * throw was fast enough to carry straight through — that is the one way
       * inertia may leave a slide — and everything slower simply slows to the
       * end of the slide, which is where a reader who threw gently expects to
       * find themselves.
       *
       * This also settles the slide exactly one screen tall. Such a slide rests
       * on both of its edges at once, so every coasting frame was opening a peek
       * and feeding the pull; a few of those in a row committed a departure
       * nobody asked for, and the page flipped between two slides.
       */
      if (coasting && (to > upperBound || to < lowerBound)) {
        setTarget(clamp(to, lowerBound, upperBound));
        return 'edge';
      }

      // Peeking is only offered where there is something to peek at, and only
      // once the track is already resting on the edge. Arriving at the edge
      // stops there instead — which is what keeps a throw made while reading
      // from spilling over into the next slide.
      if (to > upperBound && slides[index + 1]) {
        if (!coasting) reachedEdgeRef.current = true;
        if (from < upperBound - 0.5) {
          setTarget(upperBound);
          // The part of the scroll that went past the edge is not thrown away:
          // it opens the pull. Discarding it meant that during a fast scroll —
          // where the track needs several frames to settle onto the edge — every
          // notch arriving in the meantime counted for nothing, and the page sat
          // still while the wheel kept turning.
          if (!coasting) rememberPull(index, 1, to - upperBound);
          return 'edge';
        }
        const raw = rememberPull(index, 1, delta);
        peekRef.current = { index, direction: 1, raw };
        setTarget(upperBound + damp(raw, maxPeek));
        return 'peek';
      }
      if (to < lowerBound && slides[index - 1]) {
        if (!coasting) reachedEdgeRef.current = true;
        if (from > lowerBound + 0.5) {
          setTarget(lowerBound);
          if (!coasting) rememberPull(index, -1, lowerBound - to);
          return 'edge';
        }
        const raw = rememberPull(index, -1, -delta);
        peekRef.current = { index, direction: -1, raw };
        setTarget(lowerBound - damp(raw, maxPeek));
        return 'peek';
      }

      // Back inside the slide: any pull held against an edge is spent.
      pullRef.current = null;
      setTarget(clamp(to, lowerBound, upperBound));
      return 'moved';
    },
    [rememberPull, setTarget]
  );

  /**
   * Decides what an unresolved peek meant. `velocity` is the speed at release,
   * positive downwards — a hard flick commits even from a shallow pull.
   */
  /**
   * Leaves for another slide, continuing whatever movement asked for it.
   *
   * Given speed, the transition starts at that speed and decelerates from it —
   * an ease-out's initial rate is EASE_OUT_KICK × distance ÷ duration, so the
   * duration that matches an incoming speed is that ratio rearranged. Given
   * none, it keeps the deliberate ease-in-out of a departure somebody pulled
   * for.
   *
   * Either way the movement ends here: the leftover speed is spent on this
   * transition and the coast is stopped, so nothing carries on into the slide
   * that was just arrived at.
   */
  const departTo = useCallback(
    (destination: number, velocity: number) => {
      const speed = Math.abs(velocity);
      const distance = Math.abs(destination - positionRef.current);

      if (speed >= FLICK_COMMIT_VELOCITY && distance > 0) {
        const duration = clamp((EASE_OUT_KICK * distance) / speed, 220, SLIDE_TRANSITION_MS);
        tweenTo(destination, duration, easeOut);
        gateUntilRef.current = performance.now() + duration + BOUNDARY_HOLD_MS;
      } else {
        tweenTo(destination, SLIDE_TRANSITION_MS);
        gateUntilRef.current = performance.now() + SLIDE_TRANSITION_MS + BOUNDARY_HOLD_MS;
      }

      const now = performance.now();
      tailRef.current = { until: gateUntilRef.current + GATE_QUIET_MS, size: 0, cap: now + GATE_MAX_MS };

      peekRef.current = null;
      pullRef.current = null;
      velocityRef.current = 0;
      reachedEdgeRef.current = false;
      stopSettle();
    },
    [stopSettle, tweenTo]
  );

  /**
   * The slide the track is standing in, and where leaving it would land.
   */
  const departureFrom = useCallback((direction: 1 | -1): number | undefined => {
    const slides = slidesRef.current;
    const from = targetRef.current;

    let index = slides.findIndex((slide) => from <= slide.innerEnd + 0.5);
    if (index === -1) index = slides.length - 1;

    return direction > 0 ? slides[index + 1]?.start : slides[index - 1]?.innerEnd;
  }, []);

  const resolvePeek = useCallback(
    (velocity: number): boolean => {
      const peek = peekRef.current;
      if (!peek) return false;
      peekRef.current = null;

      const slides = slidesRef.current;
      const slide = slides[peek.index];
      if (!slide) return false;

      const maxPeek = viewportRefValue.current * PEEK_MAX_FACTOR;
      const edge = peek.direction > 0 ? slide.innerEnd : slide.start;
      const pulledFar = damp(peek.raw, maxPeek) >= maxPeek * PEEK_COMMIT_RATIO;
      const flicked = velocity * peek.direction >= FLICK_COMMIT_VELOCITY;

      const destination =
        peek.direction > 0 ? slides[peek.index + 1]?.start : slides[peek.index - 1]?.innerEnd;

      if ((pulledFar || flicked) && destination !== undefined) {
        departTo(destination, velocity);
        return true;
      }

      // Springs back, but takes no gate: a scroll arriving mid-bounce has to be
      // able to interrupt it and keep building on the pull already held, or the
      // notches of a mouse wheel would cancel each other out forever.
      tweenTo(edge, BOUNCE_MS);
      pullRef.current = { index: peek.index, direction: peek.direction, raw: peek.raw, at: performance.now() };
      return false;
    },
    [departTo, tweenTo]
  );

  const applyDelta = useCallback(
    (delta: number): boolean => {
      if (!Number.isFinite(delta) || delta === 0) return false;

      const now = performance.now();
      const tail = tailRef.current;
      const sinceLast = now - lastDeltaAtRef.current;
      lastDeltaAtRef.current = now;

      // Mid-transition: swallow, and take this event as the start of the tail.
      if (now < gateUntilRef.current) {
        tail.until = now + GATE_QUIET_MS;
        return false;
      }

      // The transition is over, but the gesture that caused it may not be. A
      // trackpad goes on sending deltas at frame rate for up to a second after
      // the fingers leave, and that tail used to scroll the slide just arrived
      // at — the movement that outlived the transition.
      //
      // It is swallowed for as long as it keeps arriving like a tail: without a
      // break. The first gap wider than a frame or two ends it, which is every
      // wheel notch and every new flick, so a person scrolling on is answered at
      // once. GATE_MAX_MS is the backstop for a stream that never breaks.
      if (now < tail.until && now < tail.cap && sinceLast <= TAIL_GAP_MS) {
        tail.until = now + GATE_QUIET_MS;
        return false;
      }

      tail.until = 0;
      advance(delta);
      return true;
    },
    [advance]
  );

  /** True once the pull held against the edge is already enough to leave. */
  const peekWouldCommit = useCallback((): boolean => {
    const peek = peekRef.current;
    if (!peek) return false;
    const maxPeek = viewportRefValue.current * PEEK_MAX_FACTOR;
    return damp(peek.raw, maxPeek) >= maxPeek * PEEK_COMMIT_RATIO;
  }, []);

  /**
   * What a wheel or a key does after moving the track.
   *
   * A finger reports its release, so a touch peek can wait for it — that is what
   * makes looking at the next slide and pulling back possible. A wheel never
   * releases, so it used to wait for the burst to go quiet instead, and the
   * timer restarted on every notch. Scrolling continuously therefore never
   * resolved anything: the track stalled against the edge for as long as you
   * kept scrolling, and only moved on once you stopped. Once the pull is past
   * the threshold the answer is already known, so take it now and leave the
   * idle timer for the case it was meant for — a pull that stopped short.
   */
  const resolveDriven = useCallback(() => {
    if (peekWouldCommit()) {
      cancelResolveTimer();
      resolvePeek(0);
      return;
    }
    cancelResolveTimer();
    resolveTimerRef.current = window.setTimeout(() => {
      resolveTimerRef.current = null;
      resolvePeek(0);
    }, RESOLVE_IDLE_MS);
  }, [cancelResolveTimer, peekWouldCommit, resolvePeek]);

  /**
   * Carries a throw on after the finger lifts, but only within the slide. The
   * coast ends the moment it meets an edge: momentum built up while reading is
   * not an intention to leave, so it stops there rather than spilling over.
   */
  const startSettle = useCallback(
    (initialVelocity: number) => {
      stopSettle();

      let velocity = clamp(initialVelocity, -FLING_MAX_VELOCITY, FLING_MAX_VELOCITY);
      if (Math.abs(velocity) < FLING_MIN_VELOCITY) return;

      let lastFrameAt = performance.now();

      const step = () => {
        const now = performance.now();
        const frameMs = Math.min(now - lastFrameAt, 48);
        lastFrameAt = now;

        velocity *= Math.pow(FLING_FRICTION, frameMs / 16.67);

        if (Math.abs(velocity) < FLING_MIN_VELOCITY) {
          settleRafRef.current = null;
          return;
        }

        const outcome = advance(velocity * frameMs, true);

        if (outcome !== 'moved') {
          settleRafRef.current = null;

          /**
           * The coast has met a boundary. What happens now is the whole feel of
           * the page.
           *
           * A throw that carried somebody through the slide and is still moving
           * when it arrives hands its speed straight to the departure: the
           * transition picks the movement up where the throw left it and
           * decelerates to a stop on the next slide. One movement, beginning
           * with the finger and ending on the other side — and ending there for
           * good, since departTo spends what is left of the speed.
           *
           * 'edge' is the landing frame and 'peek' the frame after, when the
           * track is already resting on the boundary and being stretched past
           * it. Both are answered, because which of the two a throw arrives on
           * is an accident of frame timing, and the reader should not be able to
           * feel the difference.
           *
           * A flick that began AT an edge hands over nothing. On a slide exactly
           * one screen tall that is every flick — such a slide has no inside to
           * be thrown through — and the deliberate peek rules decide, as they
           * always did.
           */
          /**
           * Inertia alone never leaves a slide. The reader's own scrolling has
           * to have reached the end of it — then, and only then, what is left of
           * the throw carries on into the transition.
           *
           * A throw let go in the middle of a slide drifts to the bottom and
           * stops there, which is where somebody who threw gently expects to
           * find themselves; the next scroll is what leaves. The measure used to
           * be distance travelled, which got this wrong in both directions.
           *
           * A slide with no reading range to speak of is excluded outright: it
           * is at its own end from the first pixel, so "the scroll reached the
           * end" would be true of every twitch, and the page would flip between
           * two slides.
           */
          const slides = slidesRef.current;
          const here = slides.findIndex((slide) => targetRef.current <= slide.innerEnd + 0.5);
          const readable = here === -1 ? true : !slides[here].shallow;

          const earned = reachedEdgeRef.current && readable;
          const fast = Math.abs(velocity) >= FLICK_COMMIT_VELOCITY;

          if (outcome === 'edge' && earned && fast) {
            const destination = departureFrom(velocity > 0 ? 1 : -1);
            if (destination !== undefined) {
              departTo(destination, velocity);
              return;
            }
          }

          if (outcome === 'peek') resolvePeek(earned ? velocity : 0);
          return;
        }

        settleRafRef.current = requestAnimationFrame(step);
      };

      settleRafRef.current = requestAnimationFrame(step);
    },
    [advance, departTo, departureFrom, resolvePeek, stopSettle]
  );

  const scrollToSlide = useCallback(
    (index: number) => {
      stopSettle();
      cancelResolveTimer();
      peekRef.current = null;
      pullRef.current = null;
      gateUntilRef.current = performance.now() + SLIDE_TRANSITION_MS;
      tweenTo(slidesRef.current[index]?.start ?? 0, SLIDE_TRANSITION_MS);
    },
    [cancelResolveTimer, stopSettle, tweenTo]
  );

  const scrollToTop = useCallback(() => {
    stopSettle();
    cancelResolveTimer();
    peekRef.current = null;
    pullRef.current = null;
    tweenRef.current = null;
    gateUntilRef.current = 0;
    positionRef.current = 0;
    targetRef.current = 0;
    setPosition(0);
  }, [cancelResolveTimer, stopSettle]);

  useEffect(() => {
    if (targetRef.current > maxScroll) setTarget(maxScroll);
  }, [maxScroll, setTarget]);

  // ── Input ─────────────────────────────────────────────────────────────────

  useEffect(() => {
    const viewport = viewportRef.current;
    if (!viewport) return;

    const onWheel = (event: WheelEvent) => {
      if (Math.abs(event.deltaY) < Math.abs(event.deltaX)) return;
      setInteracted(true);
      const delta = normalizeWheelDelta(event);
      if (Math.abs(delta) < 0.01) return;

      // Silence long enough means the last gesture is over: what it reached is
      // no longer this scroll's business.
      const wheelAt = performance.now();
      if (wheelAt - lastWheelAtRef.current > GESTURE_GAP_MS) reachedEdgeRef.current = false;
      lastWheelAtRef.current = wheelAt;
      event.preventDefault();
      stopSettle();
      if (applyDelta(delta)) resolveDriven();
    };

    const onTouchStart = (event: TouchEvent) => {
      if (event.touches.length === 0) return;
      setInteracted(true);
      // A hand on the screen is a new intention, and it outranks any gate left
      // over from the last one. Only wheels need to be held off after a
      // departure; a finger has already announced itself by arriving.
      gateUntilRef.current = 0;
      reachedEdgeRef.current = false;
      stopSettle();
      cancelResolveTimer();
      touchYRef.current = event.touches[0].clientY;
      touchStartRef.current = { x: event.touches[0].clientX, y: event.touches[0].clientY };
      // Only a touch that begins inside something pannable has a question to
      // answer; anywhere else the slide takes the gesture at once.
      touchAxisRef.current = horizontallyScrollable(event.target) === null ? 'vertical' : 'undecided';
      lastTouchAtRef.current = performance.now();
      velocityRef.current = 0;
    };

    const onTouchMove = (event: TouchEvent) => {
      if (event.touches.length === 0 || touchYRef.current === null) return;
      const nextY = event.touches[0].clientY;

      // The direction is decided once and then held: a table panned sideways
      // must not start dragging the page the moment the finger wavers.
      if (touchAxisRef.current !== 'vertical') {
        const start = touchStartRef.current;
        if (start === null) {
          touchAxisRef.current = 'vertical';
        } else if (touchAxisRef.current === 'undecided') {
          const travelX = Math.abs(event.touches[0].clientX - start.x);
          const travelY = Math.abs(nextY - start.y);

          if (Math.max(travelX, travelY) < AXIS_THRESHOLD_PX) {
            // Still inside the dead zone. Follow the finger without acting on
            // it, and above all without preventDefault: once this gesture is
            // cancelled the browser will not pan the table for the rest of it.
            touchYRef.current = nextY;
            lastTouchAtRef.current = performance.now();
            return;
          }

          touchAxisRef.current = travelX > travelY ? 'horizontal' : 'vertical';
        }

        if (touchAxisRef.current === 'horizontal') {
          // The browser pans the box the finger is in. The slide stays put.
          touchYRef.current = nextY;
          return;
        }
      }

      const delta = touchYRef.current - nextY;
      touchYRef.current = nextY;

      const now = performance.now();
      const elapsed = now - lastTouchAtRef.current;
      lastTouchAtRef.current = now;
      if (elapsed > 0 && elapsed < 100) {
        // Smooth the samples so one jittery frame cannot define the throw.
        velocityRef.current = velocityRef.current * VELOCITY_SMOOTHING + (delta / elapsed) * (1 - VELOCITY_SMOOTHING);
      }

      event.preventDefault();
      applyDelta(delta);
    };

    const onTouchEnd = () => {
      touchYRef.current = null;
      touchStartRef.current = null;

      // A sideways pan carries no throw for the track: it belonged to the table.
      // It still settles, with nothing behind it — a touch that lands during a
      // running settle stops it, and the slide must not be left half-way just
      // because the finger then went sideways.
      const sideways = touchAxisRef.current === 'horizontal';
      touchAxisRef.current = 'vertical';

      // A drag that ended in a pause has no throw left.
      const stale = sideways || performance.now() - lastTouchAtRef.current > 90;
      const velocity = stale ? 0 : velocityRef.current;
      velocityRef.current = 0;

      // A peek held open when the finger lifted is a deliberate attempt to
      // leave, and its speed counts. Anything else is just reading, and only
      // coasts within the slide.
      if (peekRef.current) resolvePeek(velocity);
      else startSettle(velocity);
    };

    viewport.addEventListener('wheel', onWheel, { passive: false });
    viewport.addEventListener('touchstart', onTouchStart, { passive: true });
    viewport.addEventListener('touchmove', onTouchMove, { passive: false });
    viewport.addEventListener('touchend', onTouchEnd, { passive: true });
    viewport.addEventListener('touchcancel', onTouchEnd, { passive: true });

    return () => {
      stopSettle();
      viewport.removeEventListener('wheel', onWheel);
      viewport.removeEventListener('touchstart', onTouchStart);
      viewport.removeEventListener('touchmove', onTouchMove);
      viewport.removeEventListener('touchend', onTouchEnd);
      viewport.removeEventListener('touchcancel', onTouchEnd);
    };
  }, [applyDelta, cancelResolveTimer, resolvePeek, resolveDriven, startSettle, stopSettle]);

  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => {
      // Typing a space in a form field must reach the field, not scroll.
      if (ownsKeyboardInput(event.target)) return;
      if (event.altKey || event.ctrlKey || event.metaKey) return;
      setInteracted(true);

      const page = viewportHeight * 0.82;
      if (event.key === 'ArrowDown' || event.key === 'PageDown' || event.key === ' ') {
        event.preventDefault();
        stopSettle();
        applyDelta(page);
        resolveDriven();
      } else if (event.key === 'ArrowUp' || event.key === 'PageUp') {
        event.preventDefault();
        stopSettle();
        applyDelta(-page);
        resolveDriven();
      } else if (event.key === 'Home') {
        event.preventDefault();
        stopSettle();
        cancelResolveTimer();
        peekRef.current = null;
        pullRef.current = null;
        gateUntilRef.current = performance.now() + SLIDE_TRANSITION_MS;
        tweenTo(0, SLIDE_TRANSITION_MS);
      } else if (event.key === 'End') {
        event.preventDefault();
        stopSettle();
        cancelResolveTimer();
        peekRef.current = null;
        pullRef.current = null;
        gateUntilRef.current = performance.now() + SLIDE_TRANSITION_MS;
        tweenTo(maxScroll, SLIDE_TRANSITION_MS);
      }
    };

    window.addEventListener('keydown', onKeyDown);
    return () => window.removeEventListener('keydown', onKeyDown);
  }, [applyDelta, cancelResolveTimer, maxScroll, resolveDriven, stopSettle, tweenTo, viewportHeight]);

  useEffect(
    () => () => {
      if (rafRef.current !== null) cancelAnimationFrame(rafRef.current);
      if (settleRafRef.current !== null) cancelAnimationFrame(settleRafRef.current);
      if (resolveTimerRef.current !== null) window.clearTimeout(resolveTimerRef.current);
    },
    []
  );

  return {
    viewportRef,
    contentRefs,
    viewportHeight,
    position,
    geometry,
    measured,
    interacted,
    activeIndex,
    scrollToSlide,
    scrollToTop
  };
}
