import type { RouteKey } from '../types/navigation';

export type Copy = {
  nav: {
    home: string;
    parish: string;
    cogita: string;
    faq: string;
    legal: string;
    login: string;
    account: string;
  };
  accountMenu: {
    profile: string;
    secureModeOn: string;
    secureModeOff: string;
    logout: string;
  };
  hero: {
    headline: string;
    subtitle: string;
    ctaPrimary: string;
    ctaSecondary: string;
  };
  modules: {
    title: string;
    items: Array<{
      title: string;
      desc: string;
      tag: string;
      route: RouteKey;
    }>;
  };
  access: {
    title: string;
    subtitle: string;
    login: string;
    register: string;
    loginId: string;
    password: string;
    confirm: string;
    displayName: string;
    secureMode: string;
    create: string;
    signIn: string;
    statusTitle: string;
    statusReady: string;
    loginRequired: string;
    loginError: string;
    registerError: string;
    loginTaken: string;
    passwordMismatch: string;
    passwordTooShort: string;
    passwordCommon: string;
    passwordWeak: string;
    passwordStrong: string;
    loadingLogin: string;
    loadingRegister: string;
    sessionLabel: string;
    checkSession: string;
    toggleMode: string;
    logout: string;
  };
  dashboard: {
    title: string;
    subtitle: string;
    cards: Array<{ title: string; desc: string; action: string; route?: RouteKey }>;
  };
  parish: {
    title: string;
    subtitle: string;
    items: string[];
    note: string;
    loginCta: string;
  };
  cogita: {
    title: string;
    subtitle: string;
    items: string[];
    note: string;
    loginCta: string;
    introSlides: Array<{
      id: string;
      title: string;
      subtitle?: string;
      body?: string;
      micro?: string;
      cta: string;
      secondary?: string;
    }>;
    page: {
      nav: Array<{ id: string; label: string }>;
      hero: {
        tag: string;
        title: string;
        subtitle: string;
        primaryCta: string;
        secondaryCta: string;
      };
      homeSlides: Array<{
        id: string;
        title: string;
        text: string;
        ctaLabel: string;
        variant?: 'secondary';
      }>;
      stats: Array<{ value: string; label: string }>;
      highlights: Array<{ title: string; desc: string }>;
      sections: Array<{
        id: string;
        tag: string;
        title: string;
        subtitle: string;
        cards: Array<{ title: string; desc: string; meta?: string }>;
        bullets: string[];
      }>;
      join: {
        title: string;
        subtitle: string;
        cards: Array<{ title: string; desc: string; action: string }>;
      };
    };
  };
  faq: {
    title: string;
    items: Array<{ q: string; a: string }>;
  };
  legal: {
    title: string;
    items: Array<{ title: string; desc: string }>;
  };
  account: {
    title: string;
    subtitle: string;
    overviewTitle: string;
    overviewLead: string;
    sections: {
      overview: string;
      profile: string;
      roles: string;
      security: string;
    };
    menuLabel: string;
    loginIdLabel: string;
    loginIdHint: string;
    nicknameLabel: string;
    nicknameHint: string;
    nicknamePlaceholder: string;
    nicknameToggle: string;
    nicknameAction: string;
    nicknameWorking: string;
    nicknameSuccess: string;
    nicknameError: string;
    passwordTitle: string;
    currentPassword: string;
    newPassword: string;
    confirmPassword: string;
    passwordToggle: string;
    passwordAction: string;
    passwordWorking: string;
    passwordSuccess: string;
    passwordError: string;
    secureModeTitle: string;
    secureModeNote: string;
    secureModeEnable: string;
    secureModeDisable: string;
    logoutAction: string;
    roles: {
      lead: string;
      searchPlaceholder: string;
      reachableToggle: string;
      fullscreenEnter: string;
      fullscreenExit: string;
      noFilters: string;
      loading: string;
      noNodes: string;
      panelTitle: string;
      panelEmpty: string;
      legendTitle: string;
      edgeTitle: string;
      edgeDeleteAction: string;
      edgeDeleteWorking: string;
      edgeDeleteSuccess: string;
      edgeDeleteError: string;
      linkDraftTitle: string;
      linkDraftHint: string;
      linkWorking: string;
      linkSuccess: string;
      linkError: string;
      createOwnedRole: string;
      createOwnedRoleHint: string;
      createRoleTitle: string;
      createRoleNickLabel: string;
      createRoleKindLabel: string;
      createRoleRelationLabel: string;
      createRoleAction: string;
      createRoleWorking: string;
      createRoleSuccess: string;
      createRoleError: string;
      dataAddTitle: string;
      dataFieldLabel: string;
      dataKindLabel: string;
      dataKindData: string;
      dataKindKey: string;
      dataValueLabel: string;
      dataAddAction: string;
      dataAddWorking: string;
      dataAddSuccess: string;
      dataAddError: string;
      dataEditTitle: string;
      dataEditAction: string;
      dataEditWorking: string;
      dataEditSuccess: string;
      dataEditError: string;
      dataDeleteAction: string;
      dataDeleteWorking: string;
      dataDeleteSuccess: string;
      dataDeleteError: string;
      dataOwnerLabel: string;
      dataShareTitle: string;
      dataShareTargetLabel: string;
      dataSharePermissionLabel: string;
      dataShareAction: string;
      dataShareWorking: string;
      dataShareSuccess: string;
      dataShareError: string;
      shareRoleTitle: string;
      shareRoleTargetLabel: string;
      shareRoleRelationLabel: string;
      shareRoleAction: string;
      shareRoleWorking: string;
      shareRoleSuccess: string;
      shareRoleError: string;
      shareRoleHint: string;
      recoveryPrepareAction: string;
      recoveryPrepareWorking: string;
      recoveryPrepareSuccess: string;
      recoveryPrepareError: string;
      recoveryPlanTitle: string;
      recoveryPlanHint: string;
      recoveryPlanNeedsShares: string;
      recoveryPlanLabel: string;
      recoveryPlanError: string;
      recoveryShareWorking: string;
      recoveryShareSuccess: string;
      recoveryShareError: string;
      recoveryActivateAction: string;
      recoveryActivateWorking: string;
      recoveryActivateSuccess: string;
      recoveryActivateError: string;
      contextAddRoleTitle: string;
      contextAddRolePlaceholder: string;
      contextAddRoleAction: string;
      contextAddRoleWorking: string;
      contextAddRoleSuccess: string;
      contextAddRoleError: string;
      linkPermissionNeeded: string;
      contextAddData: string;
      contextPrepareRecovery: string;
      contextClose: string;
      pendingTitle: string;
      pendingAction: string;
      pendingWorking: string;
      pendingError: string;
      pendingEmpty: string;
      pendingAccept: string;
      pendingDataTitle: string;
      pendingDataAction: string;
      pendingDataWorking: string;
      pendingDataError: string;
      pendingDataEmpty: string;
      parentsTitle: string;
      parentsAction: string;
      parentsWorking: string;
      parentsError: string;
      parentsRemoved: string;
      parentsRemoveAction: string;
      verifyTitle: string;
      verifyAction: string;
      verifyWorking: string;
      verifyError: string;
      verifyHashOk: string;
      verifyHashIssue: string;
      verifySigOk: string;
      verifySigIssue: string;
      verifyRoleSigned: string;
      relationNotesTitle: string;
      relationOwner: string;
      relationWrite: string;
      relationRead: string;
      viewGraph: string;
      viewDetails: string;
      cancelAction: string;
      incomingTitle: string;
      outgoingTitle: string;
      none: string;
    };
  };
  footer: {
    headline: string;
    contact: string;
    imprint: string;
    security: string;
  };
  loginCard: {
    title: string;
    contextDefault: string;
  };
};
