/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/rc/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcHealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rc/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcCsrfResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rc/areas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcAreasResponse"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AreasCreateAreaRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcAreaCreatedResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rc/areas/{id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcMembersResponse"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AreasAddMemberRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcMemberAddedResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rc/areas/{id}/members/{roleId}/remove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    roleId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcMemberRemovedResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rc/messages/{id}/attachments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcAttachmentsResponse"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcAttachmentUploadedResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rc/attachments/{id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rc/attachments/{id}/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcAttachmentDeletedResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rc/auth/salt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AuthSaltRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcSaltResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rc/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AuthRegisterRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcRegisteredResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rc/auth/unlock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AuthUnlockRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcSessionStartedResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rc/auth/lock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcLockedResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rc/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcLoggedOutResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rc/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcMeResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rc/auth/cache-mode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AuthCacheModeRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcCacheModeResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rc/consent/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    language?: string;
                };
                header?: never;
                path: {
                    key: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConsentConsentView"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rc/consent/{key}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    key: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcConsentVersionsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rc/consent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ConsentPublishRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcConsentPublishedResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rc/data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    roleId: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcDataItemsResponse"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DataItemsCreateRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcDataItemCreatedResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rc/data/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    purpose?: string;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcDataItemResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rc/data/{id}/share": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DataItemsShareRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcDataSharedResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rc/data/{id}/destroy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DataItemsDestroyRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcDataDestroyedResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rc/data/{id}/access-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcAccessLogResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rc/areas/{id}/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcDecisionsResponse"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DecisionsCreateDecisionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcDecisionCreatedResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rc/decisions/{id}/transition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DecisionsTransitionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcDecisionTransitionedResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rc/messages/{id}/reaction": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EngagementReactRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcReactionResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rc/areas/{id}/read-state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcReadStateResponse"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EngagementMarkReadRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcReadMarkedResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rc/areas/{id}/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    roleId: string;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcDraftResponse"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EngagementDraftRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcDraftSavedResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rc/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcInvitationsResponse"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["InvitationsCreateRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcInvitationCreatedResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rc/invitations/{id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcRevokedResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rc/invitations/peek": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["InvitationsSecretRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcInvitationPeekResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rc/invitations/redeem": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["InvitationsSecretRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcInvitationRedeemedResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rc/ledgers/{id}/head": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcLedgerHeadResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rc/ledgers/{id}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LedgerEndpointsVerifyResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rc/ledgers/{id}/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    from?: number;
                    limit?: number;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcLedgerEntriesResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rc/areas/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    roleId?: string;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcFeedResponse"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MessagesPostRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcMessagePostedResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rc/messages/{id}/edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MessagesEditRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcMessageEditedResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rc/messages/{id}/hide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MessagesHideRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcMessageHiddenResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rc/areas/{id}/polls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcPollsResponse"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PollsCreatePollRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcPollCreatedResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rc/polls/{id}/vote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PollsVoteRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcPollVotedResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rc/polls/{id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcPollClosedResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rc/recovery/shares": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcSharesResponse"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RecoveryCreateSharesRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcSharesDepositedResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rc/recovery/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcRecoveryRequestsResponse"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RecoveryRequestRecoveryRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcRecoveryRequestedResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rc/recovery/requests/{id}/object": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcObjectionResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rc/recovery/requests/{id}/contribute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RecoveryContributeRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcContributionResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rc/recovery/requests/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RecoveryCompleteRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcRecoveryCompletedResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rc/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcRolesResponse"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RolesCreateRoleRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcRoleCreatedResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rc/roles/{id}/holders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RolesAddHolderRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcHolderAddedResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rc/certificates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcCertificatesResponse"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RolesIssueRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcCertificateIssuedResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rc/certificates/{id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcRevokedResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rc/permissions/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    scopeKind: string;
                    scopeId: string;
                    capability: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcPermissionCheckResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rc/areas/{id}/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcTopicsResponse"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TopicsCreateTopicRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcTopicCreatedResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rc/topics/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TopicsAssignRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcTopicAssignedResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rc/topics/{id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TopicsCloseRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcTopicClosedResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rc/topics/{id}/labels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TopicsLabelRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RcTopicLabelsResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AreasAddMemberRequest: {
            roleId: string;
            capability?: string | null;
            grantHistory?: boolean | null;
        };
        AreasAreaView: {
            areaId: string;
            title?: string | null;
            /** Format: int32 */
            currentEpoch: number;
            lifecycle: string;
            isPublic: boolean;
            /** Format: int32 */
            readableEpochs: number;
            canWrite: boolean;
            ledgerId: string;
            canCertify: boolean;
        };
        AreasCreateAreaRequest: {
            ownerRoleId: string;
            title: string;
            isPublic?: boolean | null;
        };
        AreasMemberView: {
            roleId: string;
            capability: string;
            /** Format: date-time */
            expiresUtc: string;
            /** Format: int32 */
            epochGrants: number;
        };
        AttachmentsAttachmentView: {
            attachmentId: string;
            fileName?: string | null;
            /** Format: int64 */
            sizeBytes: number;
            /** Format: date-time */
            createdAt: string;
        };
        AuthCacheModeRequest: {
            /** Format: int32 */
            mode: number;
        };
        AuthRegisterRequest: {
            username: string;
            passwordKey: string;
            passwordSalt: string;
            displayName?: string | null;
        };
        AuthSaltRequest: {
            username: string;
        };
        AuthUnlockRequest: {
            username: string;
            passwordKey: string;
            deviceNote?: string | null;
        };
        ConsentConsentView: {
            consentKey: string;
            language: string;
            /** Format: int32 */
            version: number;
            body: string;
            bodyHash: string;
            /** Format: date-time */
            publishedAt: string;
        };
        ConsentPublishRequest: {
            consentKey: string;
            language: string;
            body: string;
            tenantRoleId: string;
        };
        DataItemsAccessEntry: {
            readerRoleId: string;
            /** Format: date-time */
            accessedAt: string;
            purpose?: string | null;
        };
        DataItemsCreateRequest: {
            ownerRoleId: string;
            dataClass: string;
            field: string;
            value: string;
            module?: string | null;
            objectType?: string | null;
        };
        DataItemsDataItemView: {
            dataItemId: string;
            ownerRoleId: string;
            dataClass: string;
            field: string;
            destroyed: boolean;
            /** Format: date-time */
            updatedAt: string;
        };
        DataItemsDestroyRequest: {
            reason?: string | null;
        };
        DataItemsShareRequest: {
            toRoleId: string;
        };
        DecisionsCreateDecisionRequest: {
            roleId: string;
            body: string;
            topicId?: string | null;
        };
        DecisionsDecisionView: {
            decisionId: string;
            state: string;
            body?: string | null;
            topicId?: string | null;
            /** Format: date-time */
            createdAt: string;
            history: components["schemas"]["DecisionsTransitionView"][];
            allowedNext: string[];
        };
        DecisionsTransitionRequest: {
            roleId: string;
            toState: string;
            reason: string;
        };
        DecisionsTransitionView: {
            fromState: string;
            toState: string;
            reason?: string | null;
            /** Format: date-time */
            at: string;
        };
        EngagementDraftRequest: {
            roleId: string;
            body: string;
        };
        EngagementMarkReadRequest: {
            roleId: string;
            /** Format: int64 */
            lastReadSeq?: number | null;
            receiptsEnabled?: boolean | null;
        };
        EngagementReactRequest: {
            roleId: string;
            /** Format: int32 */
            kind?: number | null;
        };
        EngagementReadStateView: {
            roleId: string;
            /** Format: int64 */
            lastReadSeq: number;
            /** Format: date-time */
            lastReadAt: string;
        };
        InvitationsCreateRequest: {
            roleId: string;
            label?: string | null;
            /** Format: int32 */
            daysValid?: number | null;
            /** Format: int32 */
            maxUses?: number | null;
            forSms?: boolean | null;
        };
        InvitationsInvitationView: {
            invitationId: string;
            roleId: string;
            label?: string | null;
            purpose: string;
            /** Format: date-time */
            expiresUtc: string;
            /** Format: int32 */
            useCount: number;
            /** Format: int32 */
            maxUses?: number | null;
            /** Format: date-time */
            firstOpenedUtc?: string | null;
        };
        InvitationsSecretRequest: {
            secret: string;
        };
        LedgerEndpointsEntryView: {
            /** Format: int64 */
            sequence: number;
            entryId: string;
            previousHash: string;
            entryHash: string;
            moduleId: string;
            signerKeyFingerprint: string;
            accountCommitment: string;
            /** Format: date-time */
            serverTimestamp: string;
            payloadCanonical: string;
        };
        LedgerEndpointsVerifyResponse: {
            ledgerId: string;
            /** Format: int64 */
            entries: number;
            intact: boolean;
            /** Format: int64 */
            firstBrokenSequence?: number | null;
            reason?: string | null;
            /** Format: int64 */
            headSequence: number;
            headHash: string;
        };
        MessagesEditRequest: {
            body: string;
        };
        MessagesHideRequest: {
            byAuthor?: boolean | null;
        };
        MessagesMessageView: {
            messageId: string;
            /** Format: int32 */
            epoch: number;
            authorRoleId?: string | null;
            body?: string | null;
            /** Format: int32 */
            version: number;
            /** Format: date-time */
            postedUtc: string;
            /** Format: date-time */
            editedUtc?: string | null;
            hiddenKind?: string | null;
            quoteMessageId?: string | null;
            unreadable?: string | null;
            reactions: {
                [key: string]: number;
            };
            /** Format: int32 */
            yourReaction?: number | null;
            /** Format: int32 */
            attachmentCount: number;
        };
        MessagesPostRequest: {
            authorRoleId: string;
            body: string;
            quoteMessageId?: string | null;
            chainBound?: boolean | null;
        };
        PollsCreatePollRequest: {
            question: string;
            mode?: string | null;
            reveal?: string | null;
        };
        PollsPollView: {
            pollId: string;
            question?: string | null;
            mode: string;
            reveal: string;
            closed: boolean;
            /** Format: int32 */
            voteCount: number;
            tally?: {
                [key: string]: number;
            } | null;
            yourChoice?: string | null;
        };
        PollsVoteRequest: {
            roleId: string;
            choice: string;
        };
        RcAccessLogResponse: {
            accesses: components["schemas"]["DataItemsAccessEntry"][];
        };
        RcAreaCreatedResponse: {
            areaId: string;
            tenantId: string;
            /** Format: int32 */
            epoch: number;
            title: string;
        };
        RcAreasResponse: {
            areas: components["schemas"]["AreasAreaView"][];
        };
        RcArgon2Parameters: {
            /** Format: int32 */
            memoryKiB: number;
            /** Format: int32 */
            iterations: number;
            /** Format: int32 */
            parallelism: number;
            /** Format: int32 */
            outputBytes: number;
        };
        RcAttachmentDeletedResponse: {
            attachmentId: string;
            deleted: boolean;
        };
        RcAttachmentUploadedResponse: {
            attachmentId: string;
            fileName: string;
            /** Format: int64 */
            sizeBytes: number;
            /** Format: int64 */
            quotaUsedBytes: number;
            /** Format: int64 */
            quotaBytes: number;
        };
        RcAttachmentsResponse: {
            attachments: components["schemas"]["AttachmentsAttachmentView"][];
        };
        RcCacheModeResponse: {
            /** Format: int32 */
            cacheMode: number;
            /** Format: int32 */
            forgottenBundles: number;
        };
        RcCertificateIssuedResponse: {
            certificateId: string;
            /** Format: date-time */
            expiresUtc: string;
            capability: string;
        };
        RcCertificatesResponse: {
            certificates: components["schemas"]["RolesCertificateView"][];
        };
        RcConsentPublishedResponse: {
            consentKey: string;
            language: string;
            /** Format: int32 */
            version: number;
            bodyHash: string;
        };
        RcConsentVersion: {
            language: string;
            /** Format: int32 */
            version: number;
            bodyHash: string;
            /** Format: date-time */
            publishedAt: string;
        };
        RcConsentVersionsResponse: {
            consentKey: string;
            versions: components["schemas"]["RcConsentVersion"][];
        };
        RcContributionResponse: {
            requestId: string;
            /** Format: int32 */
            contributions: number;
            /** Format: int32 */
            threshold: number;
            enough: boolean;
            alreadyContributed: boolean;
        };
        RcCsrfResponse: {
            token: string;
        };
        RcDataDestroyedResponse: {
            dataItemId: string;
            /** Format: date-time */
            destroyedAt: string;
            /** Format: int32 */
            keysDestroyed: number;
            reason?: string | null;
            ciphertextRemains: boolean;
            alreadyDestroyed: boolean;
        };
        RcDataItemCreatedResponse: {
            dataItemId: string;
            dataClass: string;
            logged: boolean;
            shareable: boolean;
        };
        RcDataItemResponse: {
            dataItemId: string;
            dataClass: string;
            field: string;
            value: string;
            logged: boolean;
        };
        RcDataItemsResponse: {
            items: components["schemas"]["DataItemsDataItemView"][];
        };
        RcDataSharedResponse: {
            dataItemId: string;
            toRoleId?: string | null;
            alreadyShared: boolean;
        };
        RcDecisionCreatedResponse: {
            decisionId: string;
            state: string;
        };
        RcDecisionTransitionedResponse: {
            decisionId: string;
            fromState: string;
            toState: string;
        };
        RcDecisionsResponse: {
            decisions: components["schemas"]["DecisionsDecisionView"][];
        };
        RcDraftResponse: {
            areaId: string;
            body?: string | null;
            /** Format: date-time */
            updatedAt?: string | null;
        };
        RcDraftSavedResponse: {
            areaId: string;
            saved: boolean;
        };
        RcFeedResponse: {
            messages: components["schemas"]["MessagesMessageView"][];
            readableEpochs: number[];
        };
        RcHealthCheck: {
            name: string;
            passed: boolean;
            detail: string;
        };
        RcHealthResponse: {
            healthy: boolean;
            checks: components["schemas"]["RcHealthCheck"][];
        };
        RcHolderAddedResponse: {
            edgeId?: string | null;
            edgeKind?: string | null;
            /** Format: date-time */
            expiresUtc?: string | null;
            alreadyHeld: boolean;
        };
        RcInvitationCreatedResponse: {
            invitationId: string;
            secret: string;
            /** Format: date-time */
            expiresUtc: string;
            purpose: string;
            /** Format: int32 */
            maxUses?: number | null;
        };
        RcInvitationPeekResponse: {
            label?: string | null;
            purpose: string;
            /** Format: date-time */
            expiresUtc: string;
            requiresAccount: boolean;
        };
        RcInvitationRedeemedResponse: {
            roleId: string;
            edgeId?: string | null;
            alreadyRedeemed: boolean;
        };
        RcInvitationsResponse: {
            invitations: components["schemas"]["InvitationsInvitationView"][];
        };
        RcLedgerEntriesResponse: {
            entries: components["schemas"]["LedgerEndpointsEntryView"][];
        };
        RcLedgerHeadResponse: {
            ledgerId: string;
            /** Format: int64 */
            sequence: number;
            hash: string;
            note: string;
        };
        RcLockedResponse: {
            locked: boolean;
            hadKeys: boolean;
        };
        RcLoggedOutResponse: {
            loggedOut: boolean;
        };
        RcMeResponse: {
            signedIn: boolean;
            accountId?: string | null;
            sessionId?: string | null;
            keysHeld?: boolean | null;
        };
        RcMemberAddedResponse: {
            roleId: string;
            capability?: string | null;
            /** Format: int32 */
            epoch: number;
            readsHistory: boolean;
            alreadyMember: boolean;
        };
        RcMemberRemovedResponse: {
            roleId: string;
            /** Format: int32 */
            newEpoch: number;
            keptWhatTheyRead: boolean;
        };
        RcMembersResponse: {
            members: components["schemas"]["AreasMemberView"][];
        };
        RcMessageEditedResponse: {
            messageId: string;
            /** Format: int32 */
            version: number;
            /** Format: date-time */
            editedUtc: string;
        };
        RcMessageHiddenResponse: {
            messageId: string;
            hidden: boolean;
            kind: string;
            reversible: boolean;
        };
        RcMessagePostedResponse: {
            messageId: string;
            /** Format: int32 */
            epoch: number;
            /** Format: int32 */
            version: number;
            /** Format: date-time */
            postedUtc: string;
            /** Format: date-time */
            appendWindowUntil: string;
            chainBound: boolean;
        };
        RcObjectionResponse: {
            requestId: string;
            objected: boolean;
        };
        RcPermissionCheckResponse: {
            allowed: boolean;
            via?: string | null;
            certificateId?: string | null;
        };
        RcPollClosedResponse: {
            pollId: string;
            closed: boolean;
        };
        RcPollCreatedResponse: {
            pollId: string;
            question: string;
            mode: string;
            reveal: string;
        };
        RcPollVotedResponse: {
            pollId: string;
            voteId: string;
        };
        RcPollsResponse: {
            polls: components["schemas"]["PollsPollView"][];
        };
        RcReactionResponse: {
            messageId: string;
            /** Format: int32 */
            kind?: number | null;
        };
        RcReadMarkedResponse: {
            areaId: string;
            /** Format: int64 */
            lastReadSeq: number;
        };
        RcReadStateResponse: {
            enabledHere: boolean;
            youAreHidden: boolean;
            readers: components["schemas"]["EngagementReadStateView"][];
        };
        RcRecoveryCompletedResponse: {
            requestId: string;
            /** Format: date-time */
            completedAt: string;
            oneTimeSecret: string;
            notice: string;
        };
        RcRecoveryRequestedResponse: {
            requestId: string;
            /** Format: date-time */
            effectiveAt: string;
            /** Format: int32 */
            graceDays: number;
            notice: string;
        };
        RcRecoveryRequestsResponse: {
            requests: components["schemas"]["RecoveryRequestView"][];
        };
        RcRegisteredResponse: {
            accountId: string;
            sessionId: string;
            /** Format: date-time */
            expiresUtc: string;
            /** Format: int32 */
            cacheMode: number;
            /** Format: int32 */
            idleMinutes: number;
            tenantId: string;
            personalRoleId: string;
        };
        RcRevokedResponse: {
            revoked: boolean;
        };
        RcRoleCreatedResponse: {
            roleId: string;
            tenantId: string;
            kind: string;
            fingerprint: string;
        };
        RcRolesResponse: {
            roles: components["schemas"]["RolesRoleView"][];
        };
        RcSaltResponse: {
            passwordSalt: string;
            argon2: components["schemas"]["RcArgon2Parameters"];
        };
        RcSessionStartedResponse: {
            accountId: string;
            sessionId: string;
            /** Format: date-time */
            expiresUtc: string;
            /** Format: int32 */
            cacheMode: number;
            /** Format: int32 */
            idleMinutes: number;
        };
        RcSharesDepositedResponse: {
            /** Format: int32 */
            guarantors: number;
            /** Format: int32 */
            threshold: number;
            /** Format: int32 */
            graceDays: number;
            notice: string;
        };
        RcSharesResponse: {
            shares: components["schemas"]["RecoveryShareView"][];
        };
        RcTopicAssignedResponse: {
            topicId: string;
            /** Format: int32 */
            assigned: number;
        };
        RcTopicClosedResponse: {
            topicId: string;
            closed: boolean;
        };
        RcTopicCreatedResponse: {
            topicId: string;
            title: string;
            /** Format: int32 */
            assigned: number;
        };
        RcTopicLabelsResponse: {
            topicId: string;
            labels: number[];
        };
        RcTopicsResponse: {
            topics: components["schemas"]["TopicsTopicView"][];
        };
        RecoveryCompleteRequest: {
            requesterRoleId: string;
        };
        RecoveryContributeRequest: {
            guarantorRoleId: string;
        };
        RecoveryCreateSharesRequest: {
            guarantorRoleIds: string[];
            /** Format: int32 */
            threshold?: number | null;
        };
        RecoveryRequestRecoveryRequest: {
            targetRoleId: string;
            byRoleId: string;
        };
        RecoveryRequestView: {
            requestId: string;
            targetRoleId: string;
            requestedByRoleId: string;
            /** Format: date-time */
            requestedAt: string;
            /** Format: date-time */
            effectiveAt: string;
            objected: boolean;
            completed: boolean;
            effective: boolean;
        };
        RecoveryShareView: {
            guarantorRoleId: string;
            /** Format: int32 */
            threshold: number;
            /** Format: int32 */
            totalShares: number;
            /** Format: date-time */
            createdAt: string;
        };
        RolesAddHolderRequest: {
            holderRoleId: string;
            edgeKind?: string | null;
            /** Format: int32 */
            daysValid?: number | null;
        };
        RolesCertificateView: {
            certificateId: string;
            subjectRoleId: string;
            scopeKind: string;
            scopeId: string;
            capability: string;
            issuedByRoleId: string;
            /** Format: date-time */
            expiresUtc: string;
        };
        RolesCreateRoleRequest: {
            holderRoleId: string;
            kind: string;
            displayName: string;
        };
        RolesIssueRequest: {
            subjectRoleId: string;
            issuerRoleId: string;
            scopeKind: string;
            scopeId: string;
            capability: string;
            /** Format: int32 */
            daysValid?: number | null;
        };
        RolesRoleView: {
            roleId: string;
            kind: string;
            tenantId: string;
            /** Format: int32 */
            depth: number;
            displayName?: string | null;
            hasKey: boolean;
        };
        TopicsAssignRequest: {
            messageIds: string[];
        };
        TopicsCloseRequest: {
            reopen?: boolean | null;
            duplicateOfId?: string | null;
        };
        TopicsCreateTopicRequest: {
            title: string;
            parentTopicId?: string | null;
            messageIds?: string[] | null;
        };
        TopicsLabelRequest: {
            labels: number[];
        };
        TopicsTopicView: {
            topicId: string;
            title?: string | null;
            parentTopicId?: string | null;
            closed: boolean;
            /** Format: int32 */
            messageCount: number;
            labels: number[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
